apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: registry
  uid: 274343a7f72dad78
spec:
  cpus: 2
  diskSize: 30GB
  image:
    oci: registry:latest
  memory: 2GB
  network:
    ports:
    - bindAddress: 0.0.0.0
      hostPort: 5000
      protocol: tcp
      vmPort: 5000
status:
  running: true
  