---
apiVersion: ignite.weave.works/v1alpha4
kind: VM
metadata:
  name: vm-team-red-005
  uid: 3a60bbf28641c5b8
spec:
  image:
    oci: chr1slavery/ignite-docker:20.04-amd64
  kernel:
    oci: weaveworks/ignite-kernel:5.14.16
  network:
    ports:
    - bindAddress: 0.0.0.0
      hostPort: 60005
      protocol: tcp
      vmPort: 22
  copyFiles:
    - hostPath: /etc/firecracker/manifests/files/daemon.json
      vmPath: /etc/docker/daemon.json
  ssh: /etc/firecracker/manifests/vm-team-red-005/id_rsa.pub
status:
  network:
    plugin: "bridge"
  running: true
